version: "3"

networks:
  mixed_cluster:
    external: true

services:
  nn-hdfs:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    hostname: nn-hdfs
    volumes:
      - /root/bigdata/volumes-nn:/hadoop/dfs/name
      - /root/workspace:/root
    environment:
      - CLUSTER_NAME=hdfs-cluster
    env_file:
      - ./hdfs.env
    ports:
    - "9870:9870"  # 将容器内的 9870 端口映射到主机的 9870 端口
    networks:
      - mixed_cluster

  dn01-hdfs:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    hostname: dn01-hdfs
    volumes:
      - /root/bigdata/volumes-dn01:/hadoop/dfs/data
    env_file:
      - ./hdfs.env
    environment:
      SERVICE_PRECONDITION: "nn-hdfs:9870"
    depends_on:
      - nn-hdfs
    networks:
      - mixed_cluster

  dn02-hdfs:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    hostname: dn02-hdfs
    volumes:
      - /root/bigdata/volumes-dn02:/hadoop/dfs/data
    env_file:
      - ./hdfs.env
    environment:
      SERVICE_PRECONDITION: "nn-hdfs:9870"
    depends_on:
      - nn-hdfs
    networks:
      - mixed_cluster

  dn03-hdfs:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    hostname: dn03-hdfs
    volumes:
      - /root/bigdata/volumes-dn03:/hadoop/dfs/data
    env_file:
      - ./hdfs.env
    environment:
      SERVICE_PRECONDITION: "nn-hdfs:9870"
    depends_on:
      - nn-hdfs
    networks:
      - mixed_cluster

  dn04-hdfs:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    hostname: dn04-hdfs
    volumes:
      - /root/bigdata/volumes-dn04:/hadoop/dfs/data
    env_file:
      - ./hdfs.env
    environment:
      SERVICE_PRECONDITION: "nn-hdfs:9870"
    depends_on:
      - nn-hdfs
    networks:
      - mixed_cluster

