version: "2.4"

x-base-service:
  &base-service
  image: linu/spark:v1
  environment: &base-env
    TZ: "Asia/Shanghai"
    SPARK_MODE: "worker"
    SPARK_MASTER_URL: "spark://master-spark:7077"
    SPARK_WORKER_MEMORY: "1G"
    SPARK_WORKER_CORES: "1"
  networks:
    - mixed_cluster

services:
  master-spark:
    image: linu/spark:v1
    hostname: master-spark
    networks:
      - mixed_cluster
    environment:
      - TZ=Asia/Shanghai
      - SPARK_MODE=master
    volumes:
      - /root/workspace:/root
    ports:
      - "8080:8080" # Spark Management UI
    cpuset: "28-31" 
  
  w01-spark:
    <<: *base-service
    hostname: w01-spark
    networks:
      - mixed_cluster
    depends_on:
      - master-spark
    cpuset: "1" 
  w02-spark:
    <<: *base-service
    hostname: w02-spark
    networks:
      - mixed_cluster
    depends_on:
      - master-spark
    cpuset: "2" 
  w03-spark:
    <<: *base-service
    hostname: w03-spark
    networks:
      - mixed_cluster
    depends_on:
      - master-spark
    cpuset: "3" 
  w04-spark:
    <<: *base-service
    hostname: w04-spark
    networks:
      - mixed_cluster
    depends_on:
      - master-spark
    cpuset: "4" 
  w05-spark:
    <<: *base-service
    hostname: w05-spark
    networks:
      - mixed_cluster
    depends_on:
      - master-spark
    cpuset: "5" 
  w06-spark:
    <<: *base-service
    hostname: w06-spark
    networks:
      - mixed_cluster
    depends_on:
      - master-spark
    cpuset: "6" 
  w07-spark:
    <<: *base-service
    hostname: w07-spark
    networks:
      - mixed_cluster
    depends_on:
      - master-spark
    cpuset: "7" 
  w08-spark:
    <<: *base-service
    hostname: w08-spark
    networks:
      - mixed_cluster
    depends_on:
      - master-spark
    cpuset: "8" 
  w09-spark:
    <<: *base-service
    hostname: w09-spark
    networks:
      - mixed_cluster
    depends_on:
      - master-spark
    cpuset: "9" 
  w10-spark:
    <<: *base-service
    hostname: w10-spark
    networks:
      - mixed_cluster
    depends_on:
      - master-spark
    cpuset: "10" 
  w11-spark:
    <<: *base-service
    hostname: w11-spark
    networks:
      - mixed_cluster
    depends_on:
      - master-spark
    cpuset: "11"
  w12-spark:
    <<: *base-service
    hostname: w12-spark
    networks:
      - mixed_cluster
    depends_on:
      - master-spark
    cpuset: "12"
  w13-spark:
    <<: *base-service
    hostname: w13-spark
    networks:
      - mixed_cluster
    depends_on:
      - master-spark
    cpuset: "13"
  w14-spark:
    <<: *base-service
    hostname: w14-spark
    networks:
      - mixed_cluster
    depends_on:
      - master-spark
    cpuset: "14"
  w15-spark:
    <<: *base-service
    hostname: w15-spark
    networks:
      - mixed_cluster
    depends_on:
      - master-spark
    cpuset: "15"
  w16-spark:
    <<: *base-service
    hostname: w16-spark
    networks:
      - mixed_cluster
    depends_on:
      - master-spark
    cpuset: "16"
networks:
  mixed_cluster:
    external: true
